### ISSUE TITLE
Feature: support labeling pull requests

### ISSUE THREAD

**Issue by GrantBirki** [nobe4/gh-ln#5]
Pretty self-explanatory. It would be useful to have PRs opened with certain labels ✨.

```yaml
links:
  - from:
      repo: nobe4/repo-1
      path: README.md
    to:
      - repo: nobe4/repo-2
        path: README.md
      - repo: nobe4/repo-3
        path: README.md
      - repo: nobe4/repo-4
        path: README.md
        labels: # something like this
          - action-ln
          - automatic-update
```

It would be a bonus to bake this into the [Global Defaults](https://github.com/nobe4/action-ln/issues/81) as well.

Just wanted to open an issue as I think this would be a nifty feature later on.
