### ISSUE TITLE
Support glob matching `*` in a single directory

### ISSUE THREAD

**Issue by nobe4** [nobe4/gh-ln#6]
This enables linking a collection of files in a directory.

E.g.

```yaml
- from: nobe4/action-ln:.github/workflows/*
  to: nobe4/test

# nobe4/action-ln:.github/workflows/ci.yaml => nobe4/test:.github/workflows/ci.yaml
# nobe4/action-ln:.github/workflows/test.yaml => nobe4/test:.github/workflows/test.yaml
# nobe4/action-ln:.github/workflows/ln.yaml => nobe4/test:.github/workflows/ln.yaml
# ...
```

- [ ] Write coherent specs
- [ ] Implement
- [ ] Test

> [!NOTE]
> This will be interesting to implement, since the config parsing is currently completely static.

## Specs

E.g. tree

```
.
├── a
│   ├── b
│   ├── c
│   └── d
│       ├── e
│       └── f
├── g
└── h
```

-
  ```yaml
  - from: *
  
  # src:g => dst:g
  # src:h => dst:h
  ```

-
  ```yaml
  - from: a/*
  
  # src:a/b => dst:a/b
  # src:a/c => dst:a/c
  ```
  or
  ```yaml
  - from: a/*
  
  # src:a/b => dst:b
  # src:a/c => dst:c
  ```

-
  ```yaml
  - from: a/*
    to:   d
  
  # src:a/b => dst:d/b
  # src:a/c => dst:d/c
  ```
  or
  ```yaml
  - from: a/*
    to:   d
  
  # src:a/b => dst:d/a/b
  # src:a/c => dst:d/a/c
  ```

-
  ```yaml
  - from: a/d/*
    to:   d
  
  # src:a/d/e => dst:d/e
  # src:a/d/f => dst:d/f
  ```
  or
  ```yaml
  - from: a/d/*
    to:   d
  
  # src:a/d/e => dst:d/a/d/e
  # src:a/d/f => dst:d/a/d/f
  ```
